runtime: nodejs20

handlers:
  # This handes routes all requests not caught above to your main app.
  # It is required when static routers are defined, but can be omitted
  # (along with the entire handlers section) when there are no static files 
  # defined. 
- url: /.*
  script: auto