name: Bug report
description: Report something that is broken in PawMatch
title: "[Bug]: "
labels: ["bug"]

body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How badly does this bug impact users?
      options:
        - Blocking (app unusable)
        - High (major feature broken)
        - Medium (workaround exists)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the bug?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
